version: "3.4"
services:

  db:
    image: postgres:16.1
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pokemon}
      POSTGRES_USER: ${POSTGRES_USER:-ash}
      POSTGRES_DB: ${POSTGRES_DB:-pokeapi}
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  apir1:
    image: valtergranatoneto/apir1:01
    ports:
      - "8081:8080"
    depends_on:
      - db
    restart: always

  pgadmin4:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "valtergranaton@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
      PGADMIN_LISTEN_PORT: 9000
    ports:
      - "9000:9000"
    volumes:
      - pgadmin_data:/pgadmin4/servers.json


volumes:
  pg_data:
  pgadmin_data:
