version: "3.4"
services:

  db:
    image: postgres:16.1
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-8w4YWvH8zX12}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-pokeapi}
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432

  #apir1:
  #  image: valtergranatoneto/apir1:01
  #  ports:
  #    - "8081:8080"
  #  depends_on:
  #    - db
  #  restart: always


  #apir2:
  #  image: valtergranatoneto/apir2:01
  #  ports:
  #    - "8082:8080"
  #  depends_on:
  #    - db
  #  restart: always


  #apig:
  #  image: valtergranatoneto/apig:01
  #  ports:
  #    - "9001:8080"
  #  depends_on:
  #    - db
  #  restart: always


  pgadmin4:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "valtergranaton@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
      PGADMIN_LISTEN_PORT: 9001
    ports:
      - "9001:9001"
    volumes:
      - pgadmin_data:/pgadmin4/servers.json
    
volumes:
  pg_data:
  pgadmin_data:
